### ISSUE TITLE
축제 리스트 수정

### ISSUE THREAD

**Issue by ho991217** [ToyVallet/swifty-fe#19]
## 현재 축제 리스트 이미지
<img width="428" alt="스크린샷 2024-05-17 09 23 26" src="https://github.com/ToyVallet/swifty-fe/assets/84632077/72003c08-e903-429c-a345-7891254883c0">
<img width="428" alt="스크린샷 2024-05-17 09 23 37" src="https://github.com/ToyVallet/swifty-fe/assets/84632077/fb9da54d-abb4-4944-81dd-e29c5ecbd55a">

### 이슈
- [x] 포스터를 클릭해도 해당 학교 라인업 페이지로 이동하지 않습니다.
- [x] 포스터 하단에 그라디언트가 들어가있는데, 이것은 디자인과 다릅니다.
- [x] 포스터 모서리에 곡률 (`border-radius`)가 들어가지 않았습니다.
- [x] 페스티벌 전체보기 (`/ko/festivals`) 페이지에서 광고 배너의 너비가 디자인과 다릅니다.

**Comment by kd02109** [comment]
LGTM
